# app/routers/excel.py
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel

from app.core.excel_processor import render_excel_from_json

# -----------------
# Logger (simple)
# -----------------
logger = logging.getLogger("excel")
if not logger.handlers:
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s - %(message)s"))
    logger.addHandler(handler)
logger.setLevel(logging.INFO)

# -----------------
# Router
# -----------------
router = APIRouter(prefix="/api", tags=["excel"])


class ExcelRenderRequest(BaseModel):
    data: Dict[str, Any]
    detail_sheet_name: Optional[str] = "別紙"


def _resolve_template() -> Path:
    """
    Locate template.xlsx robustly:
      1) env TEMPLATE_XLSX
      2) app/template.xlsx
      3) project_root/template.xlsx
      4) cwd/template.xlsx
    """
    import os

    # .../app/routers/excel.py -> parents[2] == .../app
    app_root = Path(__file__).resolve().parents[2]

    candidates = [
        Path(env) if (env := os.getenv("TEMPLATE_XLSX")) else None,
        app_root / "template.xlsx",
        app_root.parent / "template.xlsx",
        Path.cwd() / "template.xlsx",
    ]
    for p in (c for c in candidates if c):
        if p.exists():
            return p
    raise HTTPException(
        status_code=500,
        detail="template.xlsx not found in expected locations.",
    )


@router.post("/excel/render")
def excel_render(req: ExcelRenderRequest):
    try:
        data = req.data or {}
        if not isinstance(data, dict) or not data:
            raise HTTPException(status_code=400, detail="request.data is empty or invalid dict.")

        items = data.get("items") or []
        logger.info(f"[excel] keys={list(data.keys())} items_len={len(items)}")

        template_path = _resolve_template()
        logger.info(f"[excel] using template: {template_path}")

        xlsx = render_excel_from_json(
            data=data,
            template_path=template_path,
            detail_sheet_name=req.detail_sheet_name or "別紙",
        )

        size = len(xlsx) if xlsx else 0
        logger.info(f"[excel] generated bytes={size}")
        if size == 0:
            raise HTTPException(status_code=500, detail="render returned 0 bytes.")

        return Response(
            content=xlsx,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": 'attachment; filename="generated.xlsx"'},
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception(e)
        raise HTTPException(status_code=500, detail=f"excel render failed: {e}")
